"""intento 7 segunda pregunta

Revision ID: 165efdf544c2
Revises: 30576a7fbeae
Create Date: 2023-12-01 14:17:29.419235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "165efdf544c2"
down_revision: Union[str, None] = "30576a7fbeae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
