"""3° intento quinta pregunta

Revision ID: 1ebcc35f0986
Revises: 472f33de2e8b
Create Date: 2023-12-03 14:34:49.858016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebcc35f0986'
down_revision: Union[str, None] = '472f33de2e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
