"""otro intento quinta pregunta

Revision ID: 29a72f64c25e
Revises: 41b83f6ebecc
Create Date: 2023-12-03 19:42:01.432461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a72f64c25e'
down_revision: Union[str, None] = '41b83f6ebecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_loans', sa.Column('loan_date', sa.Date(), nullable=False))
    op.drop_column('book_loans', 'date_loan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_loans', sa.Column('date_loan', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('book_loans', 'loan_date')
    # ### end Alembic commands ###
