"""4° intento quinta pregunta

Revision ID: 41b83f6ebecc
Revises: 1ebcc35f0986
Create Date: 2023-12-03 14:47:31.116573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b83f6ebecc'
down_revision: Union[str, None] = '1ebcc35f0986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
