"""1° intento quinta pregunta

Revision ID: 46cf552386e2
Revises: 7b9435ad6d2d
Create Date: 2023-12-02 17:07:07.799262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cf552386e2'
down_revision: Union[str, None] = '7b9435ad6d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_Loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('loan_date', sa.Date(), nullable=True),
    sa.Column('days_loan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id', 'client_id', 'book_id')
    )
    op.add_column('books', sa.Column('available_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'available_amount')
    op.drop_table('book_Loans')
    # ### end Alembic commands ###
