"""3° intento quinta pregunta

Revision ID: 472f33de2e8b
Revises: 0387c1e7fec7
Create Date: 2023-12-03 11:46:35.689745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "472f33de2e8b"
down_revision: Union[str, None] = "0387c1e7fec7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
