"""9 intento quinta pregunta

Revision ID: 52e748ee2f3b
Revises: cc27457323ef
Create Date: 2023-12-03 20:51:56.001799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52e748ee2f3b"
down_revision: Union[str, None] = "cc27457323ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
