"""4° intento segunda actividad

Revision ID: 79e51ab5060f
Revises: ffd9af8b9340
Create Date: 2023-12-01 11:44:55.684491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e51ab5060f'
down_revision: Union[str, None] = 'ffd9af8b9340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
