"""Implementacion cuarta pregunta

Revision ID: 7b9435ad6d2d
Revises: 5da981149ce1
Create Date: 2023-12-01 15:45:43.932626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b9435ad6d2d"
down_revision: Union[str, None] = "5da981149ce1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
