"""5° intento segunda pregunta

Revision ID: 8523cf918a88
Revises: 79e51ab5060f
Create Date: 2023-12-01 11:49:53.328924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8523cf918a88"
down_revision: Union[str, None] = "79e51ab5060f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
