"""11 intento quinta pregunta

Revision ID: 854c37b92bf4
Revises: 95af3ad25bbc
Create Date: 2023-12-04 00:08:41.258631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "854c37b92bf4"
down_revision: Union[str, None] = "95af3ad25bbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "as",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("days_loans", sa.Integer(), nullable=False),
        sa.Column("loan_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("book_loans")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_loans",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("book_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("days_loans", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("loan_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], name="book_loans_book_id_fkey"),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], name="book_loans_client_id_fkey"),
        sa.PrimaryKeyConstraint("id", "book_id", "client_id", name="book_loans_pkey"),
    )
    op.drop_table("as")
    # ### end Alembic commands ###
