"""11 intento quinta pregunta

Revision ID: 95af3ad25bbc
Revises: c5e5195cebc4
Create Date: 2023-12-03 21:39:34.885379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95af3ad25bbc'
down_revision: Union[str, None] = 'c5e5195cebc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
