"""otro intento quinta pregunta

Revision ID: a75f2c18232f
Revises: 4f3a5d5a33be
Create Date: 2023-12-03 20:30:16.238426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a75f2c18232f"
down_revision: Union[str, None] = "4f3a5d5a33be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
