"""10 intento quinta pregunta

Revision ID: c5e5195cebc4
Revises: c6d1953e5683
Create Date: 2023-12-03 21:26:25.831406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5e5195cebc4"
down_revision: Union[str, None] = "c6d1953e5683"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
