"""intento 5? de la primera actividad

Revision ID: f06dfb370e88
Revises: d3d34fe91cba
Create Date: 2023-12-01 10:38:11.287496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06dfb370e88'
down_revision: Union[str, None] = 'd3d34fe91cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
